version: "3"

services:
  redis1:
    image: redis
    container_name: redis1
    ports:
      - "6379"
    command: ["redis-server", "/usr/local/etc/redis/redis1.conf"]
    volumes:
      - ./redis1.conf:/usr/local/etc/redis/redis1.conf
    networks:
      - redis_network

  redis2:
    image: redis
    container_name: redis2
    ports:
      - "6380"
    command: ["redis-server", "/usr/local/etc/redis/redis2.conf"]
    volumes:
      - ./redis2.conf:/usr/local/etc/redis/redis2.conf
    networks:
      - redis_network

  redis3:
    image: redis
    container_name: redis3
    ports:
      - "6381"
    command: ["redis-server", "/usr/local/etc/redis/redis3.conf"]
    volumes:
      - ./redis3.conf:/usr/local/etc/redis/redis3.conf
    networks:
      - redis_network

networks:
  redis_network:
    driver: bridge

